### ISSUE TITLE
FilesystemExportCommand needs to use @Argument

### ISSUE THREAD

**Issue by lseinc** [novotnyr/aedile#1]
I am unable to get FilesystemExportCommand to export to a directory.  It says it requires an option, but there is no way to provide it based on the setup.  Based on previous changes in FilesystemImportCommand, I believe you probably wanted the same change for FilesystemExportCommand.  

-import org.kohsuke.args4j.Option;
 +import org.kohsuke.args4j.Argument;
  
  public class FilesystemImportCommand {
 -    @Option(name = "directory", required = true)
 +    @Argument(metaVar = "directory")

**Comment by novotnyr** [comment]
This is fixed in 47ab638e1845bc0d7a93f904598313089c3d6bb1 and released in 0.3.
